include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ DEFAULT RULES THAT I WANT TO CHANGE ------ #
    #                       ---                         #
    # ------------------------------------------------- #
    # Use this behind instance members
    unnecessary_this: false

    # TODO: enable when this rule is fixed
    # Sort dependencies alphabetically
    sort_pub_dependencies: false


    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    # TODO: enable when 'Key' type values are not caught by this rule
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: false

    # Good packages document everything
    # TODO: enable later to make docs on everything
    public_member_api_docs: false

    # The new tabs vs. spaces. Choose wisely (not relevant)
    #prefer_single_quotes: true
    #prefer_double_quotes: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Back to the 80s (not relevant)
    #lines_longer_than_80_chars: true
